version: '3'
services:
    api:
        build:
            context: .
            target: test
        ports:
            - '3000:3000'
        volumes:
            - /app/node_modules
            - .:/app